ACTIVE_STORES = [
    {
        "code": "UTAWALA",
        "name": "Utawala",
        "status": "active",
        "address": "Utawala, Nairobi",
        "latitude": -1.2866,
        "longitude": 36.9651,
        "google_maps_url": "https://maps.google.com/?q=Utawala+Nairobi",
        "catchment_area": "机场通勤与社区零售",
        "manager_note": "现有主力门店",
    },
    {
        "code": "PAIPLINE",
        "name": "Paipline",
        "status": "active",
        "address": "Pipeline, Nairobi",
        "latitude": -1.3173,
        "longitude": 36.8959,
        "google_maps_url": "https://maps.google.com/?q=Pipeline+Nairobi",
        "catchment_area": "住宅区与街边人流",
        "manager_note": "价格敏感型门店",
    },
    {
        "code": "KINNO",
        "name": "Kinno",
        "status": "active",
        "address": "Kinno, Nairobi",
        "latitude": -1.3001,
        "longitude": 36.8447,
        "google_maps_url": "https://maps.google.com/?q=Kinno+Nairobi",
        "catchment_area": "社区与通勤混合人流",
        "manager_note": "适合做对比门店",
    },
]

DEFAULT_SUPPLIERS = [
    {
        "code": "YOUXUN",
        "name": "Youxun Demo",
        "contact_person": "Youxun Team",
        "phone": "",
        "status": "active",
        "note": "海运包裹默认测试供应商",
    },
    {
        "code": "SUPDEMO",
        "name": "Supplier Demo",
        "contact_person": "Demo Buyer",
        "phone": "",
        "status": "active",
        "note": "商品建档默认测试供应商",
    },
    {
        "code": "DEMOSUP",
        "name": "Demo Supplier",
        "contact_person": "Warehouse Demo",
        "phone": "",
        "status": "active",
        "note": "仓库收货默认测试供应商",
    },
    {
        "code": "SMOKESUP",
        "name": "Smoke Supplier",
        "contact_person": "Smoke Test",
        "phone": "",
        "status": "active",
        "note": "自动化测试供应商",
    },
]

DEFAULT_CARGO_TYPES = [
    {
        "code": "SUMMERAPP",
        "name": "summer apparel",
        "status": "active",
        "note": "夏装与轻薄服装原始包裹",
    },
    {
        "code": "SHOES",
        "name": "shoes",
        "status": "active",
        "note": "鞋类原始包裹",
    },
    {
        "code": "BAGS",
        "name": "bags",
        "status": "active",
        "note": "包类原始包裹",
    },
    {
        "code": "COSMETICS",
        "name": "cosmetics",
        "status": "active",
        "note": "美妆百货原始包裹",
    },
]

ROLE_DEFINITIONS = [
    {"code": "admin", "name": "最高权限", "scope": "global"},
    {"code": "warehouse_clerk", "name": "分拣员", "scope": "warehouse"},
    {"code": "warehouse_supervisor", "name": "仓库主管", "scope": "warehouse"},
    {"code": "store_manager", "name": "店长", "scope": "store"},
    {"code": "store_clerk", "name": "店员", "scope": "store"},
    {"code": "cashier", "name": "收银员", "scope": "store"},
    {"code": "area_supervisor", "name": "区域运营经理", "scope": "multi_store"},
    {"code": "external_auditor", "name": "外部审计", "scope": "readonly"},
]

DEFAULT_USERS = [
    {
        "username": "admin_1",
        "full_name": "System Admin",
        "role_code": "admin",
        "store_code": None,
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "warehouse_clerk_1",
        "full_name": "Warehouse Clerk 1",
        "role_code": "warehouse_clerk",
        "store_code": None,
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "warehouse_supervisor_1",
        "full_name": "Warehouse Supervisor 1",
        "role_code": "warehouse_supervisor",
        "store_code": None,
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "store_manager_1",
        "full_name": "Utawala Store Manager",
        "role_code": "store_manager",
        "store_code": "UTAWALA",
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "store_clerk_1",
        "full_name": "Utawala Store Clerk 1",
        "role_code": "store_clerk",
        "store_code": "UTAWALA",
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "Austin",
        "full_name": "Austin",
        "role_code": "store_clerk",
        "store_code": "UTAWALA",
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "Swahili",
        "full_name": "Swahili",
        "role_code": "store_clerk",
        "store_code": "UTAWALA",
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "cashier_1",
        "full_name": "Utawala Cashier 1",
        "role_code": "cashier",
        "store_code": "UTAWALA",
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "area_supervisor_1",
        "full_name": "Area Supervisor 1",
        "role_code": "area_supervisor",
        "store_code": None,
        "is_active": True,
        "password": "demo1234",
    },
    {
        "username": "auditor_1",
        "full_name": "External Auditor",
        "role_code": "external_auditor",
        "store_code": None,
        "is_active": True,
        "password": "demo1234",
    },
]

BARCODE_SETTINGS = {
    "type": "Code128",
    "printer_model": "Deli DL-720C",
    "approval_role_for_transfer": "warehouse_supervisor",
    "pos_mode": "web_pos_on_windows",
}

WAREHOUSE_IN_LAYOUT = {
    "paper_preset": "60x40",
    "components": [
        {"id": "warehouse_in_top_supplier", "label": "左上供应商", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 0.0, "w_mm": 34.2, "h_mm": 5.6, "font_size": 13.4, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "top_supplier"},
        {"id": "warehouse_in_top_major", "label": "左上大类", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 4.8, "w_mm": 34.2, "h_mm": 5.2, "font_size": 12.2, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "top_major"},
        {"id": "warehouse_in_top_minor", "label": "左上小类", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 9.6, "w_mm": 34.2, "h_mm": 4.6, "font_size": 10.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "top_minor"},
        {"id": "warehouse_in_piece_current", "label": "右上当前包序", "type": "text", "enabled": True, "x_mm": 40.8, "y_mm": 0.0, "w_mm": 17.2, "h_mm": 6.0, "font_size": 12.2, "font_weight": "700", "align": "center", "vertical_align": "top", "render_mode": "bitmap", "content_source": "piece_current"},
        {"id": "warehouse_in_piece_total", "label": "右上总包数", "type": "text", "enabled": True, "x_mm": 40.8, "y_mm": 5.6, "w_mm": 17.2, "h_mm": 6.0, "font_size": 12.2, "font_weight": "700", "align": "center", "vertical_align": "top", "render_mode": "bitmap", "content_source": "piece_total"},
        {"id": "warehouse_in_top_divider", "label": "中部横线", "type": "line", "enabled": True, "x_mm": 2.4, "y_mm": 16.6, "w_mm": 54.2, "h_mm": 0.88, "content_source": "none"},
        {"id": "warehouse_in_barcode", "label": "左下条码", "type": "barcode", "enabled": True, "x_mm": 2.8, "y_mm": 20.0, "w_mm": 26.8, "h_mm": 15.2, "align": "center", "content_source": "scan_token"},
        {"id": "warehouse_in_lower_vertical_divider", "label": "下半区竖线", "type": "line", "enabled": True, "x_mm": 30.4, "y_mm": 20.0, "w_mm": 0.88, "h_mm": 16.2, "content_source": "none"},
        {"id": "warehouse_in_trace_code", "label": "右下短码", "type": "text", "enabled": True, "x_mm": 31.8, "y_mm": 20.0, "w_mm": 24.8, "h_mm": 3.4, "font_size": 9.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "trace_code"},
        {"id": "warehouse_in_trace_batch", "label": "右下批次", "type": "text", "enabled": True, "x_mm": 31.8, "y_mm": 23.9, "w_mm": 24.8, "h_mm": 3.4, "font_size": 9.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "trace_batch"},
        {"id": "warehouse_in_trace_shipment", "label": "右下船单", "type": "text", "enabled": True, "x_mm": 31.8, "y_mm": 27.8, "w_mm": 24.8, "h_mm": 3.4, "font_size": 9.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "trace_shipment"},
        {"id": "warehouse_in_trace_inbound", "label": "右下入仓时间", "type": "text", "enabled": True, "x_mm": 31.8, "y_mm": 31.7, "w_mm": 24.8, "h_mm": 3.4, "font_size": 9.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "trace_inbound"},
        {"id": "warehouse_in_middle_divider", "label": "下部横线", "type": "line", "enabled": True, "x_mm": 2.4, "y_mm": 37.1, "w_mm": 54.2, "h_mm": 0.88, "content_source": "none"},
    ],
}

TRANSTOSHOP_LAYOUT = {
    "paper_preset": "60x40",
    "components": [
        {"id": "transtoshop_store_name", "label": "左上门店", "type": "text", "enabled": True, "x_mm": 2.6, "y_mm": 2.0, "w_mm": 27.4, "h_mm": 6.8, "font_size": 30.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "store_name"},
        {"id": "transtoshop_transfer_order", "label": "左上调货单号", "type": "text", "enabled": True, "x_mm": 2.6, "y_mm": 9.4, "w_mm": 27.4, "h_mm": 3.6, "font_size": 17.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "transfer_order_no"},
        {"id": "transtoshop_bale_piece_summary", "label": "左上件位", "type": "text", "enabled": True, "x_mm": 2.6, "y_mm": 13.6, "w_mm": 27.4, "h_mm": 3.0, "font_size": 17.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "bale_piece_summary"},
        {"id": "transtoshop_outbound_time", "label": "左上出库时间", "type": "text", "enabled": True, "x_mm": 2.6, "y_mm": 16.9, "w_mm": 27.4, "h_mm": 1.4, "font_size": 10.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "outbound_time"},
        {"id": "transtoshop_total_quantity", "label": "右上总数", "type": "text", "enabled": True, "x_mm": 31.6, "y_mm": 2.6, "w_mm": 24.0, "h_mm": 3.6, "font_size": 16.0, "font_weight": "700", "align": "right", "vertical_align": "top", "render_mode": "bitmap", "content_source": "total_quantity"},
        {"id": "transtoshop_packing_list", "label": "右侧箱单", "type": "text", "enabled": True, "x_mm": 31.6, "y_mm": 7.2, "w_mm": 24.0, "h_mm": 28.4, "font_size": 6.2, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "packing_list"},
        {"id": "transtoshop_barcode", "label": "左下条码", "type": "barcode", "enabled": True, "x_mm": 2.8, "y_mm": 20.0, "w_mm": 26.8, "h_mm": 15.2, "align": "center", "content_source": "dispatch_bale_no"},
        {"id": "transtoshop_lower_vertical_divider", "label": "下半区竖线", "type": "line", "enabled": True, "x_mm": 30.4, "y_mm": 20.0, "w_mm": 0.88, "h_mm": 16.2, "content_source": "none"},
        {"id": "transtoshop_short_code", "label": "左下短码", "type": "text", "enabled": True, "x_mm": 2.8, "y_mm": 36.0, "w_mm": 26.8, "h_mm": 2.1, "font_size": 10.0, "font_weight": "700", "align": "center", "vertical_align": "top", "render_mode": "bitmap", "content_source": "dispatch_bale_no"},
    ],
}

WAIT_FOR_TRANSTOSHOP_LAYOUT = {
    "paper_preset": "60x40",
    "components": [
        {"id": "wait_for_transtoshop_status", "label": "顶部状态", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 1.4, "w_mm": 54.8, "h_mm": 5.6, "font_size": 20.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "status"},
        {"id": "wait_for_transtoshop_cat", "label": "类别", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 7.4, "w_mm": 31.0, "h_mm": 4.0, "font_size": 16.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "cat"},
        {"id": "wait_for_transtoshop_sub", "label": "小类", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 11.6, "w_mm": 31.0, "h_mm": 4.2, "font_size": 15.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "sub"},
        {"id": "wait_for_transtoshop_grade", "label": "等级", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 15.8, "w_mm": 24.0, "h_mm": 3.6, "font_size": 14.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "grade"},
        {"id": "wait_for_transtoshop_qty", "label": "数量", "type": "text", "enabled": True, "x_mm": 37.0, "y_mm": 7.4, "w_mm": 20.0, "h_mm": 4.4, "font_size": 18.0, "font_weight": "700", "align": "right", "vertical_align": "top", "render_mode": "bitmap", "content_source": "qty"},
        {"id": "wait_for_transtoshop_divider", "label": "中部分隔", "type": "line", "enabled": True, "x_mm": 2.4, "y_mm": 20.4, "w_mm": 54.8, "h_mm": 0.7, "content_source": "none"},
        {"id": "wait_for_transtoshop_code", "label": "短码文本", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 22.2, "w_mm": 54.8, "h_mm": 3.0, "font_size": 12.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "code"},
        {"id": "wait_for_transtoshop_barcode", "label": "条码", "type": "barcode", "enabled": True, "x_mm": 2.4, "y_mm": 26.0, "w_mm": 55.2, "h_mm": 9.0, "align": "center", "content_source": "dispatch_bale_no"},
        {"id": "wait_for_transtoshop_barcode_text", "label": "人眼码", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 35.8, "w_mm": 40.0, "h_mm": 2.2, "font_size": 11.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "dispatch_bale_no"},
    ],
}

STORE_LOOSE_PICK_60X40_LAYOUT = {
    "paper_preset": "60x40",
    "components": [
        {"id": "store_loose_pick_status", "label": "顶部门店与品类", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 1.2, "w_mm": 54.8, "h_mm": 4.6, "font_size": 16.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "status"},
        {"id": "store_loose_pick_cat", "label": "单据类型", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 6.2, "w_mm": 26.0, "h_mm": 3.0, "font_size": 11.5, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "cat"},
        {"id": "store_loose_pick_grade", "label": "封包上限", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 9.4, "w_mm": 26.0, "h_mm": 3.0, "font_size": 10.5, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "grade"},
        {"id": "store_loose_pick_qty", "label": "拣货数量", "type": "text", "enabled": True, "x_mm": 36.0, "y_mm": 6.2, "w_mm": 21.0, "h_mm": 3.4, "font_size": 14.0, "font_weight": "700", "align": "right", "vertical_align": "top", "render_mode": "bitmap", "content_source": "qty"},
        {"id": "store_loose_pick_packing_list", "label": "分拣明细", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 13.0, "w_mm": 54.8, "h_mm": 9.0, "font_size": 6.2, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "packing_list"},
        {"id": "store_loose_pick_divider", "label": "中部分隔", "type": "line", "enabled": True, "x_mm": 2.4, "y_mm": 22.8, "w_mm": 54.8, "h_mm": 0.7, "content_source": "none"},
        {"id": "store_loose_pick_code", "label": "短码文本", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 24.0, "w_mm": 54.8, "h_mm": 2.5, "font_size": 10.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "code"},
        {"id": "store_loose_pick_barcode", "label": "条码", "type": "barcode", "enabled": True, "x_mm": 2.4, "y_mm": 27.0, "w_mm": 55.2, "h_mm": 8.0, "align": "center", "content_source": "dispatch_bale_no"},
        {"id": "store_loose_pick_barcode_text", "label": "人眼码", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 36.0, "w_mm": 40.0, "h_mm": 2.2, "font_size": 10.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "dispatch_bale_no"},
    ],
}

WAIT_FOR_SALE_LAYOUT = {
    "paper_preset": "60x40",
    "components": [
        {"id": "wait_for_sale_status", "label": "顶部状态", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 1.4, "w_mm": 54.8, "h_mm": 5.6, "font_size": 20.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "status"},
        {"id": "wait_for_sale_cat", "label": "类别", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 7.4, "w_mm": 29.0, "h_mm": 4.0, "font_size": 16.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "cat"},
        {"id": "wait_for_sale_qty", "label": "数量", "type": "text", "enabled": True, "x_mm": 39.0, "y_mm": 7.4, "w_mm": 18.0, "h_mm": 4.0, "font_size": 17.0, "font_weight": "700", "align": "right", "vertical_align": "top", "render_mode": "bitmap", "content_source": "qty"},
        {"id": "wait_for_sale_sub", "label": "小类", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 11.6, "w_mm": 31.0, "h_mm": 4.0, "font_size": 15.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "sub"},
        {"id": "wait_for_sale_grade", "label": "等级", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 15.8, "w_mm": 19.0, "h_mm": 3.6, "font_size": 14.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "grade"},
        {"id": "wait_for_sale_weight", "label": "重量", "type": "text", "enabled": True, "x_mm": 25.0, "y_mm": 15.8, "w_mm": 32.0, "h_mm": 3.6, "font_size": 14.0, "font_weight": "700", "align": "right", "vertical_align": "top", "render_mode": "bitmap", "content_source": "weight"},
        {"id": "wait_for_sale_divider", "label": "中部分隔", "type": "line", "enabled": True, "x_mm": 2.4, "y_mm": 20.4, "w_mm": 54.8, "h_mm": 0.7, "content_source": "none"},
        {"id": "wait_for_sale_code", "label": "短码文本", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 22.2, "w_mm": 54.8, "h_mm": 3.0, "font_size": 12.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "code"},
        {"id": "wait_for_sale_barcode", "label": "条码", "type": "barcode", "enabled": True, "x_mm": 2.4, "y_mm": 26.0, "w_mm": 55.2, "h_mm": 9.0, "align": "center", "content_source": "dispatch_bale_no"},
        {"id": "wait_for_sale_barcode_text", "label": "人眼码", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 35.8, "w_mm": 40.0, "h_mm": 2.2, "font_size": 11.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "dispatch_bale_no"},
    ],
}

CLOTHES_RETAIL_LAYOUT = {
    "paper_preset": "60x40",
    "components": [
        {"id": "clothes_retail_price", "label": "左上价格", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 2.2, "w_mm": 33.0, "h_mm": 12.0, "font_size": 42.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "price"},
        {"id": "clothes_retail_product_name", "label": "商品名", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 15.0, "w_mm": 33.0, "h_mm": 6.2, "font_size": 22.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "product_name"},
        {"id": "clothes_retail_short_suffix", "label": "右上短后缀", "type": "text", "enabled": True, "x_mm": 38.0, "y_mm": 3.8, "w_mm": 18.0, "h_mm": 4.8, "font_size": 15.0, "font_weight": "700", "align": "center", "vertical_align": "middle", "render_mode": "bitmap", "content_source": "short_suffix"},
        {"id": "clothes_retail_divider", "label": "中部分隔线", "type": "line", "enabled": True, "x_mm": 2.4, "y_mm": 22.1, "w_mm": 55.2, "h_mm": 0.7, "content_source": "none"},
        {"id": "clothes_retail_barcode", "label": "底部条码", "type": "barcode", "enabled": True, "x_mm": 2.4, "y_mm": 24.0, "w_mm": 55.2, "h_mm": 9.8, "align": "center", "content_source": "barcode_value"},
        {"id": "clothes_retail_barcode_text", "label": "底部短码文本", "type": "text", "enabled": True, "x_mm": 2.4, "y_mm": 34.5, "w_mm": 40.0, "h_mm": 3.0, "font_size": 11.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "barcode_value"},
    ],
}

DEPARTMENT_RETAIL_LAYOUT = {
    "paper_preset": "40x30",
    "components": [
        {"id": "department_retail_price", "label": "左上价格", "type": "text", "enabled": True, "x_mm": 1.4, "y_mm": 1.2, "w_mm": 22.6, "h_mm": 8.8, "font_size": 30.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "price"},
        {"id": "department_retail_short_suffix", "label": "右上短后缀", "type": "text", "enabled": True, "x_mm": 27.4, "y_mm": 1.8, "w_mm": 10.6, "h_mm": 4.6, "font_size": 13.0, "font_weight": "700", "align": "center", "vertical_align": "middle", "render_mode": "bitmap", "content_source": "short_suffix"},
        {"id": "department_retail_product_name", "label": "商品名", "type": "text", "enabled": True, "x_mm": 1.4, "y_mm": 10.8, "w_mm": 36.0, "h_mm": 5.0, "font_size": 14.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "product_name"},
        {"id": "department_retail_divider", "label": "分隔线", "type": "line", "enabled": True, "x_mm": 1.4, "y_mm": 16.8, "w_mm": 36.6, "h_mm": 0.6, "content_source": "none"},
        {"id": "department_retail_barcode", "label": "底部条码", "type": "barcode", "enabled": True, "x_mm": 1.2, "y_mm": 18.0, "w_mm": 37.0, "h_mm": 8.8, "align": "center", "content_source": "barcode_value"},
        {"id": "department_retail_barcode_text", "label": "底部短码文本", "type": "text", "enabled": True, "x_mm": 1.4, "y_mm": 27.2, "w_mm": 28.0, "h_mm": 2.2, "font_size": 9.0, "font_weight": "700", "align": "left", "vertical_align": "top", "render_mode": "bitmap", "content_source": "barcode_value"},
    ],
}

LABEL_TEMPLATES = [
    {
        "template_code": "bale_60x40",
        "name": "Bale Label 60x40",
        "template_scope": "bale",
        "description": "入仓一包一码默认模板，适合标准 60x40 不干胶。",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["barcode_value", "supplier_name", "category_main", "category_sub", "package_position"],
        "is_active": True,
    },
    {
        "template_code": "bale_50x30",
        "name": "Bale Compact 50x30",
        "template_scope": "bale",
        "description": "更紧凑的入仓贴码模板，适合窄幅打印纸。",
        "width_mm": 50,
        "height_mm": 30,
        "barcode_type": "Code128",
        "fields": ["barcode_value", "supplier_name", "category_main", "package_position"],
        "is_active": True,
    },
    {
        "template_code": "warehouse_in",
        "name": "warehouse in",
        "template_scope": "bale",
        "description": "锁定当前仓库入仓标签版式，适合 60x40 入仓贴码。",
        "paper_preset": "60x40",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["barcode_value", "supplier_name", "category_main", "category_sub", "serial_no", "total_packages", "shipment_no", "parcel_batch_no", "received_at"],
        "layout": WAREHOUSE_IN_LAYOUT,
        "is_active": True,
    },
    {
        "template_code": "transtoshop",
        "name": "transtoshop",
        "template_scope": "warehouseout_bale",
        "description": "仓库出库 / 门店签收标签固定模板，适合 60x40 warehouseout bale 标签。",
        "paper_preset": "60x40",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["store_name", "transfer_order_no", "bale_piece_summary", "outbound_time", "total_quantity", "packing_list", "dispatch_bale_no"],
        "layout": TRANSTOSHOP_LAYOUT,
        "is_active": True,
    },
    {
        "template_code": "wait_for_transtoshop",
        "name": "WAITING FOR STORE DISPATCH",
        "template_scope": "warehouseout_bale",
        "description": "待送店 60x40 正式模板，锁定当前 WF-A WAITING FOR STORE DISPATCH 版式。",
        "paper_preset": "60x40",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["status", "cat", "sub", "grade", "qty", "code", "dispatch_bale_no"],
        "layout": WAIT_FOR_TRANSTOSHOP_LAYOUT,
        "is_active": True,
    },
    {
        "template_code": "store_loose_pick_60x40",
        "name": "门店补差拣货单 60x40",
        "template_scope": "warehouseout_bale",
        "description": "门店补货散货补差拣货单模板，给工人按一张 LPK barcode 拣货并贴补差包。",
        "paper_preset": "60x40",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["status", "cat", "grade", "qty", "packing_list", "code", "dispatch_bale_no"],
        "layout": STORE_LOOSE_PICK_60X40_LAYOUT,
        "is_active": True,
    },
    {
        "template_code": "wait_for_sale",
        "name": "wait for sale",
        "template_scope": "warehouseout_bale",
        "description": "待销售 60x40 正式模板，锁定当前 WF-B wait for sale 版式。",
        "paper_preset": "60x40",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["status", "cat", "sub", "grade", "qty", "weight", "code", "dispatch_bale_no"],
        "layout": WAIT_FOR_SALE_LAYOUT,
        "is_active": True,
    },
    {
        "template_code": "apparel_60x40",
        "name": "Apparel Label",
        "template_scope": "product",
        "description": "商品条码标签模板。",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["product_name", "barcode"],
        "is_active": True,
    },
    {
        "template_code": "clothes_retail",
        "name": "clothes retail",
        "template_scope": "product",
        "description": "门店最终商品标签固定模板，锁定当前 SI-A 价格主版。",
        "paper_preset": "60x40",
        "width_mm": 60,
        "height_mm": 40,
        "barcode_type": "Code128",
        "fields": ["price", "product_name", "short_suffix", "barcode_value"],
        "layout": CLOTHES_RETAIL_LAYOUT,
        "is_active": True,
    },
    {
        "template_code": "general_40x30",
        "name": "General Label",
        "template_scope": "product",
        "description": "通用商品小标签模板。",
        "width_mm": 40,
        "height_mm": 30,
        "barcode_type": "Code128",
        "fields": ["product_name", "barcode"],
        "is_active": True,
    },
    {
        "template_code": "department_retail",
        "name": "department retail",
        "template_scope": "product",
        "description": "百货商品 40x30 正式模板，锁定当前 DI-A 百货清晰版。",
        "paper_preset": "40x30",
        "width_mm": 40,
        "height_mm": 30,
        "barcode_type": "Code128",
        "fields": ["price", "product_name", "short_suffix", "barcode_value"],
        "layout": DEPARTMENT_RETAIL_LAYOUT,
        "is_active": True,
    },
]

STORE_RACK_TEMPLATE = [
    {"rack_code": "PT-SW", "category_hint": "sweat pant"},
    {"rack_code": "PT-CR", "category_hint": "cargo pant"},
    {"rack_code": "PT-JE", "category_hint": "jeans pant"},
    {"rack_code": "PT-OT", "category_hint": "other pants"},
    {"rack_code": "DR-L", "category_hint": "long dress"},
    {"rack_code": "DR-S", "category_hint": "short dress"},
    {"rack_code": "LT-2P", "category_hint": "2 pieces"},
    {"rack_code": "JK-OT", "category_hint": "jacket"},
    {"rack_code": "LT-TP", "category_hint": "lady tops"},
    {"rack_code": "TS-UN", "category_hint": "unisex t-shirt"},
    {"rack_code": "MS-SH", "category_hint": "men shirt"},
    {"rack_code": "MS-PL", "category_hint": "men polo"},
    {"rack_code": "KD-BB", "category_hint": "baby kids"},
    {"rack_code": "KD-BK", "category_hint": "big kids"},
    {"rack_code": "SH-SP", "category_hint": "sport shoes"},
    {"rack_code": "SH-OF", "category_hint": "office shoes"},
    {"rack_code": "SH-LD", "category_hint": "lady shoes"},
    {"rack_code": "SH-KD", "category_hint": "kids shoes"},
]
